services:
  zookeeper1:
    image: zookeeper:3.9
    container_name: zookeeper1
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888
    ports:
      - "2181:2181"
    networks:
      - zk-net

  zookeeper2:
    image: zookeeper:3.9
    container_name: zookeeper2
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888
    networks:
      - zk-net
      
  zookeeper3:
    image: zookeeper:3.9
    container_name: zookeeper3
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888
    networks:
      - zk-net

  api1:
    build:
      context: ./app
    container_name: api1
    environment:
      ZOOKEEPER_HOSTS: "zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
    ports:
      - "8001:8000"
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    networks:
      - zk-net

  api2:
    build:
      context: ./app
    container_name: api2
    environment:
      ZOOKEEPER_HOSTS: "zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
    ports:
      - "8002:8000"
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    networks:
      - zk-net

  api3:
    build:
      context: ./app
    container_name: api3
    environment:
      ZOOKEEPER_HOSTS: "zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
    ports:
      - "8003:8000"
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    networks:
      - zk-net

networks:
  zk-net:
    driver: bridge
